# Generated by Django 5.1.7 on 2025-04-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_profile_options_remove_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
