# Generated by Django 5.1.7 on 2025-04-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_dish_discounted_price_dish_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='discount_price_display',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
